version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server
    ports:
      - "6378:6379"
    volumes:
      - redis_data2:/data

volumes:
  redis_data2:
    driver: local